version: '3.8'
services:
  openperf1:
    user: "${UID}:${GID}"  # 添加这一行关键配置
    image: openperf:latest
    build: $T1_HOME
    container_name: openperf1
    network_mode: host
    tty: true               # 对应 -t 参数
    stdin_open: true        # 对应 -i 参数
    volumes:
      # 挂载目录
      - "${T1_HOME}/GEM5:/home/openperf/GEM5"
      - "${T1_HOME}/NEMU:/home/openperf/NEMU"
      - "${T1_HOME}/nexus-am:/home/openperf/nexus-am"
      - "${T1_HOME}/openperf:/home/openperf/openperf"
      - "${T1_HOME}/script:/home/openperf/script"
      
      # 挂载单个文件
      - "${T1_HOME}/riscv64-nemu-interpreter-c1469286ca32-so:/home/openperf/riscv64-nemu-interpreter-c1469286ca32-so"
      - "${T1_HOME}/Makefile:/home/openperf/Makefile"
