version: '3.8'
services:
  openperf1:
    user: "${UID}:${GID}"  # 添加这一行关键配置
    image: openperf:latest
    build: $T1_HOME
    container_name: openperf1
    network_mode: host
    tty: true               # 对应 -t 参数
    stdin_open: true        # 对应 -i 参数
    volumes:
      # 挂载目录
      - "${T1_HOME}:/home/openperf"
